###set

GET http://localhost:8880/redis/set/123/test
Accept: application/json

###get

GET http://localhost:8880/redis/get/DOC_VOTE_6_127.0.0.1
Accept: application/json

###

###delete

GET http://localhost:8880/redis/delete/DOC_VOTE_5_127.0.0.1
Accept: application/json

###
